@set ARMHOME=%DEV_ROOT%\ARM\ADSv1_2
@set PATH=%DEV_ROOT%\ARM\ADSv1_2\BIN;%PATH%
@set ARMCONF=%DEV_ROOT%\ARM\ADSv1_2\BIN
@set ARMDLL=%DEV_ROOT%\ARM\ADSv1_2\BIN
@set ARMINC=%DEV_ROOT%\ARM\ADSv1_2\INCLUDE
@set ARMLIB=%DEV_ROOT%\ARM\ADSv1_2\LIB
